In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.roll(a,1,axis=0)) #shift down

[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [6]:
print(np.roll(a,1,axis=1)) # shift right

[[3 1 2]
 [6 4 5]
 [9 7 8]]


In [8]:
print(np.roll(a,-1,axis=0)) # shift up

[[4 5 6]
 [7 8 9]
 [1 2 3]]
