In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.roll(a,1,axis=0)) #shift down

[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [3]:
print(np.roll(a,1,axis=1)) # shift right

[[3 1 2]
 [6 4 5]
 [9 7 8]]


In [4]:
print(np.roll(a,-1,axis=0)) # shift up

[[4 5 6]
 [7 8 9]
 [1 2 3]]


In [12]:
a=np.array([1,2])
b=[]
b.append([a for i in range(3)])
b=np.array(b)
print(b.shape)

(1, 3, 2)
